name: 🐛 Bug Report
description: Report an issue that should be fixed
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a bug report.

        If you need help or support using our loom, and are not reporting a bug, please
        join our [Discord](https://teaclient.net/discord) server.

        Make sure you are running the latest version of our loom.

        Please check for other issues to see you are experiencing may already have been reported.
        Please try to include as much information as possible.

  - type: input
    attributes:
      label: What version of loom are you running?
  - type: textarea
    attributes:
      label: What steps can reproduce the bug?
      description: Explain how to reproduce the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the expected behavior?
      description: If possible, please provide text.
  - type: textarea
    attributes:
      label: What do you see instead?
      description: If possible, please provide text.
  - type: textarea
    attributes:
      label: Additional information
      description: Is there anything else you think we should know?
